name: learn-github-actions
run-name: ${{ action.actor }} is learning Github Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest # base image 지정
    steps: # uses랑 run 두가지 사용가능 uses는 미리 정의된 action이라는 절차를 사용 run은 cmd에서 사용하는 것들을 사용
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats # bats: 테스팅할 때 쓰는 framework
      - run: bats -v
